packages:
  - name: sveltekit
    functions:
      - name: endpoint
        runtime: nodejs:18
        web: raw
        limits:
          timeout: 5000
          memory: 1024
environment:
  BASE_URL: "${BASE_URL}"
