packages:
  - name: sveltekit
    functions:
      - name: endpoint
        main: build/index.js
        runtime: nodejs:18
        web: raw
        limits:
          timeout: 5000
          memory: 512
environment:
  BASE_URL: "${BASE_URL}"
